// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcbbcaciqbclmdmktrei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjYmJjYWNpcWJjbG1kbWt0cmVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MzE2MzksImV4cCI6MjA2MDEwNzYzOX0.yYUHwv9EdF3lIvmyWeOdOq82DFmDTw-ZSuYghFL2y20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);